# name to display in GitHub Actions
name: Check PR Requirements

on:
  # Allows to manually run the job
  workflow_dispatch:
  pull_request:
  
jobs:
    check-requirements:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
    
        - name: Run Python PR check Script
          run: |
             python .github/workflows/scripts/check-pr-requirements.py