# name to display in GitHub Actions
name: Generate Readme Files

on:
  # Allows to manually run the job
  workflow_dispatch:
  
  push:
    branches:
    - main  
    
jobs:
  generate-readme-files:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run Python script
      run: python generate_readme.py