on:
    pull_request:
  
jobs:
    check-requirements:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: List subfolders
          run: |
            find external -type d -print0 | xargs -0 echo
        - name: Check requirements in each subfolder
          run: |
            find external -type d -print0 | xargs -0 -I subfolder sh -c 'cd subfolder && ./check_subfolder_requirements.sh'

